[package]
name = "orbit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.28.6"

# logging
fern = { version = "0.6.2", features = ["colored"] }
log = "0.4.18"
log-panics = "2.1.0"
